TARGET = bin/list

SOURCES = src/dump_functions.cpp \
		  src/list_functions.cpp \
		  src/list_main.cpp \
		  src/list_set_get_functions.cpp

BUILD_DIR = build

OBJECTS = $(addprefix $(BUILD_DIR)/, $(notdir $(SOURCES:.cpp=.o)))

CXX = g++

CXX_STANDARD = -std=c++20

OPTIMIZATION =

DEBUG_FLAGS = -g -D BENCHMARK_MODE -DNDEBUG

WARNING_FLAGS = -Wall -Wextra -Weffc++ \
                -Waggressive-loop-optimizations \
                -Wc++14-compat \
                -Wmissing-declarations \
                -Wcast-align \
                -Wcast-qual \
                -Wchar-subscripts \
                -Wconditionally-supported \
                -Wconversion \
                -Wctor-dtor-privacy \
                -Wempty-body \
                -Wfloat-equal \
                -Wformat-nonliteral \
                -Wformat-security \
                -Wformat-signedness \
                -Wformat=2 \
                -Winline \
                -Wlogical-op \
                -Wnon-virtual-dtor \
                -Wopenmp-simd \
                -Woverloaded-virtual \
                -Wpacked \
                -Wpointer-arith \
                -Winit-self \
                -Wredundant-decls \
                -Wshadow \
                -Wsign-conversion \
                -Wsign-promo \
                -Wstrict-null-sentinel \
                -Wstrict-overflow=2 \
                -Wsuggest-attribute=noreturn \
                -Wsuggest-final-methods \
                -Wsuggest-final-types \
                -Wsuggest-override \
                -Wswitch-default \
                -Wswitch-enum \
                -Wsync-nand \
                -Wundef \
                -Wunreachable-code \
                -Wuseless-cast \
                -Wvariadic-macros \
                -Wno-literal-suffix \
                -Wno-missing-field-initializers \
                -Wno-narrowing \
                -Wno-old-style-cast \
                -Wno-varargs \
                -Wstack-protector \
                -Wlarger-than=8192 \
                -Wstack-usage=8192 \
                -Werror=vla \
				-fcheck-new \
				-fsized-deallocation \
				-fstack-protector \
				-fstrict-overflow \
				-flto-odr-type-merging \
				-pie -fPIE

SANITIZER_FLAGS =
LDFLAGS = $(SANITIZER_FLAGS)

CXXFLAGS = $(OPTIMIZATION) $(DEBUG_FLAGS) $(WARNING_FLAGS) $(SANITIZER_FLAGS) $(CXX_STANDARD)

$(TARGET): $(BUILD_DIR) $(OBJECTS)
	$(CXX) $(OBJECTS) -o $@ $(LDFLAGS)

$(BUILD_DIR)/%.o: src/%.cpp | $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(TARGET) $(OBJECTS)
	rm -f $(BUILD_DIR)/*.o 

