TARGET = bin/hash_table

LIST_BUILD_DIR = ../List/build
LIST_OBJECTS = $(LIST_BUILD_DIR)/dump_functions.o \
               $(LIST_BUILD_DIR)/list_functions.o \
               $(LIST_BUILD_DIR)/list_set_get_functions.o

SRC_DIR = src
SOURCES = $(SRC_DIR)/hash_table_main.cpp \
          $(SRC_DIR)/hash_table_funcs.cpp \
          $(SRC_DIR)/hash_table_dump_funcs.cpp \
          $(SRC_DIR)/parse_db_from_file.cpp \

BUILD_DIR = build
OBJECTS = $(addprefix $(BUILD_DIR)/, $(notdir $(SOURCES:.cpp=.o)))

CXX = g++
CXX_STANDARD = -std=c++20
OPTIMIZATION = -O3 -mavx2
DEBUG_FLAGS = -g -D _DEBUG -ggdb3 -fno-omit-frame-pointer

WARNING_FLAGS = -Wall -Wextra -Weffc++ \
                -Waggressive-loop-optimizations \
                -Wc++14-compat \
                -Wmissing-declarations \
                -Wcast-align \
                -Wcast-qual \
                -Wchar-subscripts \
                -Wconditionally-supported \
                -Wconversion \
                -Wctor-dtor-privacy \
                -Wempty-body \
                -Wfloat-equal \
                -Wformat-nonliteral \
                -Wformat-security \
                -Wformat-signedness \
                -Wformat=2 \
                -Winline \
                -Wlogical-op \
                -Wnon-virtual-dtor \
                -Wopenmp-simd \
                -Woverloaded-virtual \
                -Wpacked \
                -Wpointer-arith \
                -Winit-self \
                -Wredundant-decls \
                -Wshadow \
                -Wsign-conversion \
                -Wsign-promo \
                -Wstrict-null-sentinel \
                -Wstrict-overflow=2 \
                -Wsuggest-attribute=noreturn \
                -Wsuggest-final-methods \
                -Wsuggest-final-types \
                -Wsuggest-override \
                -Wswitch-default \
                -Wswitch-enum \
                -Wsync-nand \
                -Wundef \
                -Wunreachable-code \
                -Wuseless-cast \
                -Wvariadic-macros \
                -Wno-literal-suffix \
                -Wno-missing-field-initializers \
                -Wno-narrowing \
                -Wno-old-style-cast \
                -Wno-varargs \
                -Wstack-protector \
                -Wlarger-than=8192 \
                -Wstack-usage=8192 \
                -Werror=vla \
				-fcheck-new \
				-fsized-deallocation \
				-fstack-protector \
				-fstrict-overflow \
				-flto-odr-type-merging \
				-pie -fPIE

SANITIZER_FLAGS = -fsanitize=address,alignment,bool,bounds,enum,float-cast-overflow,float-divide-by-zero,integer-divide-by-zero,leak,nonnull-attribute,null,object-size,return,returns-nonnull-attribute,shift,signed-integer-overflow,undefined,unreachable,vla-bound,vptr

LDFLAGS = $(SANITIZER_FLAGS)
INCLUDES = -I ../List/include  \
           -I include  \

CXXFLAGS = $(OPTIMIZATION) $(DEBUG_FLAGS) $(WARNING_FLAGS) $(SANITIZER_FLAGS) $(CXX_STANDARD) $(INCLUDES)

$(TARGET): $(BUILD_DIR) $(OBJECTS) $(LIST_OBJECTS)
	$(CXX) $(OBJECTS) $(LIST_OBJECTS) -o $@ $(LDFLAGS)

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp | $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

clean:
	rm -f $(TARGET) $(OBJECTS)

.PHONY: clean