TARGET = bin/hash_table

LIST_BUILD_DIR = ../List/build
LIST_OBJECTS = $(LIST_BUILD_DIR)/dump_functions.o \
               $(LIST_BUILD_DIR)/list_functions.o \
               $(LIST_BUILD_DIR)/list_set_get_functions.o

SRC_DIR = src
BUILD_DIR = build

SOURCES_CXX = $(SRC_DIR)/hash_table_main.cpp \
              $(SRC_DIR)/hash_table_funcs.cpp \
              $(SRC_DIR)/hash_table_dump_funcs.cpp \
              $(SRC_DIR)/parse_db_from_file.cpp \
              $(SRC_DIR)/hash_table_test_funcs.cpp \
              $(SRC_DIR)/hash_table_stat_funcs.cpp \

SOURCES_ASM = $(wildcard $(SRC_DIR)/*.asm)

OBJECTS_CXX = $(patsubst $(SRC_DIR)/%.cpp, $(BUILD_DIR)/%.o, $(SOURCES_CXX))
OBJECTS_ASM = $(patsubst $(SRC_DIR)/%.asm, $(BUILD_DIR)/%.o, $(SOURCES_ASM))
OBJECTS = $(OBJECTS_CXX) $(OBJECTS_ASM)

CXX = g++
NASM = nasm

ASM_FLAGS = -f elf64 -F dwarf

CXX_STANDARD =
OPTIMIZATION = -O3 -march=native
DEBUG_FLAGS = -g -D BENCHMARK_MODE -DNDEBUG

WARNING_FLAGS = -Wall -Wextra -Weffc++ \
                -Waggressive-loop-optimizations \
                -Wc++14-compat \
                -Wmissing-declarations \
                -Wcast-align \
                -Wcast-qual \
                -Wchar-subscripts \
                -Wconditionally-supported \
                -Wconversion \
                -Wctor-dtor-privacy \
                -Wempty-body \
                -Wfloat-equal \
                -Wformat-nonliteral \
                -Wformat-security \
                -Wformat-signedness \
                -Wformat=2 \
                -Winline \
                -Wlogical-op \
                -Wnon-virtual-dtor \
                -Wopenmp-simd \
                -Woverloaded-virtual \
                -Wpacked \
                -Wpointer-arith \
                -Winit-self \
                -Wredundant-decls \
                -Wshadow \
                -Wsign-conversion \
                -Wsign-promo \
                -Wstrict-null-sentinel \
                -Wstrict-overflow=2 \
                -Wsuggest-attribute=noreturn \
                -Wsuggest-final-methods \
                -Wsuggest-final-types \
                -Wsuggest-override \
                -Wswitch-default \
                -Wswitch-enum \
                -Wsync-nand \
                -Wundef \
                -Wunreachable-code \
                -Wuseless-cast \
                -Wvariadic-macros \
                -Wno-literal-suffix \
                -Wno-missing-field-initializers \
                -Wno-narrowing \
                -Wno-old-style-cast \
                -Wno-varargs \
                -Wstack-protector \
                -Wlarger-than=8192 \
                -Wstack-usage=8192 \
                -Werror=vla \
                -fcheck-new \
                -fsized-deallocation \
                -fstack-protector \
                -fstrict-overflow \
                -flto-odr-type-merging \
                -pie -fPIE

SANITIZER_FLAGS =

LDFLAGS = $(SANITIZER_FLAGS)

INCLUDES = -I ../List/include -I include

CXXFLAGS = $(OPTIMIZATION) $(DEBUG_FLAGS) $(WARNING_FLAGS) $(SANITIZER_FLAGS) $(CXX_STANDARD) $(INCLUDES)

.PHONY: all clean clean-all

all: $(TARGET)

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.asm | $(BUILD_DIR)
	$(NASM) $(ASM_FLAGS) $< -o $@

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp | $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(TARGET): $(BUILD_DIR) $(OBJECTS) $(LIST_OBJECTS)
	$(CXX) $(OBJECTS) $(LIST_OBJECTS) -o $@ $(LDFLAGS)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

clean:
	rm -f $(TARGET) $(OBJECTS)

clean-all: clean
	rm -rf $(BUILD_DIR)